eik-lib/common

.eslintrc
lib/index.js
lib/read-file.js
lib/stream.js
package.json
test/read-file.js

This moves a couple of functions from core to this library. We want to reuse these in ex the Google Cloud Storage sink.

Moving common functions from core

---

lib/classes/read-file.js
lib/index.js
test/classes/read-file.js

This ads a `.mimeType` property to the ReadFile class so this info can come from the sinks and not further up in the layers.

Add .mimeType property to ReadFile class

---

lib/classes/sink.js
lib/index.js
test/classes/sink.js

Loose idea; The sinks is a vital part of Eik and the idea is that anyone should be able to implement a Sink to write and read files from any storage which suite them. Though, internally in Eik we depend on a specific API of the sink for this to work.
This is a small Sink interface which a custom sink should extend and override its method of to make sure the implementation adhere to this specific API. Iow; for a implementor of a sink, she would have to do as follow:
```js
const { Sink } = require('@eik/common');
const CustomSink = class CustomSink extends Sink {
constructor() {
super();
}
write() { /* Custom code */ }
read() { /* Custom code */ }
delete() { /* Custom code */ }
exist() { /* Custom code */ }
}
```
In `@eik/core` if the Sink does not extend this interface, `@eik/core` will …

Provide a Sink Interface

---

lib/validators/index.js
test/validators/index.js

Adds "npm" to type validator so it can be used as a namespace in URLs.

Add "npm" as valid value to type validators

---

lib/schemas/eikjson.schema.json
test/schemas/index.js

Needed to loosen up the schema to accommodate npm package names and globs in paths

fix: loosen validation

---

README.md
lib/schemas/assert.js
lib/schemas/index.js
test/schemas/assert.js

Due to the way ajv validation works, I ended up having to check errors and throw repeatedly in many places. I though it would be much nicer to have an “asserts” function for each validation so that you can just call Eg. `asserts.name(“@finn-no/thing”)` which will throw on error with a nice error message.

Add assert functions

---

README.md
lib/helpers/index.js
lib/helpers/local-assets.js
lib/helpers/package-url.js
lib/index.js
lib/utils/files.js
lib/utils/index.js
package.json
test/helpers/eik.json
test/helpers/local-assets.test.js
test/helpers/package-url.test.js

This PR adds a couple helpers to remove a bunch of typical boiler plate in app setups.
The `localAssets` function adds development routes to an Express or Fastify app based on values it reads from the app's `eik.json` file
```js
await localAssets(app);
```
The `packageURL` function creates asset URLs based on the values in the app's `eik.json` file. You give it the get you want from the `eik.json` files object and it returns a URL object. 
```js
const url = await packageURL('esm.js');
// in prod you'd use url.href
// in dev you'd use url.pathname in conjuction with adding dev routes using the localAssets function
```

feat: add helpers for development and production

---

lib/classes/eik-config.js
test/classes/eik-config.test.js
test/helpers/config-store.test.js

Why: This is what is allowed according to the schema.

Ensure map property for config is always an array

---

lib/helpers/local-assets.js
lib/helpers/package-url.js

Silly me, of course this came back to bite me. There are cases where you want to load different eik.json files. With these singletons, this wasn't possible.

fix: remove singletons in packageURL and localAssets

---

lib/classes/eik-config.js
lib/helpers/config-store.js
test/classes/eik-config.test.js
test/helpers/config-store.test.js

This means that consumers of configuration that wish to bump the version of the eik pkg can now do so without worrying about how to persist the config correctly.

Add config persistence to config store

---

README.md
lib/schemas/assert.js
lib/schemas/eikjson.schema.json
lib/schemas/validate.js
test/schemas/assert.js
test/schemas/index.js

Begins work on https://github.com/eik-lib/issues/issues/1 by adding a `type` field to the schema

feat: add "type" field to JSON Schema, validation and asserts

---

lib/classes/eik-config.js
lib/classes/invalid-config-error.js
lib/helpers/config-store.js
lib/schemas/validate.js
test/classes/eik-config.test.js
test/helpers/config-store.test.js
test/schemas/assert.js

Adds type field
Changes validation method to no longer mutate subject being validated
Adds validation to config class constructor and setters
BREAKING CHANGE: valid eik config object is now required when instantiating EikConfig class

feat!: add type field to eik config schema

---

lib/classes/eik-config.js
test/classes/eik-config.test.js

I couldn't get AJV to use the default value in the schema when validating a single value so I've moved to just hard coding the default value.

fix: correctly return default type from eik-config class

---

lib/helpers/config-store.js
test/helpers/config-store.test.js

This makes it so that config will ignore package.json files whenever an eik key is not defined (in package.json)

fix: do not use package.json as config source if eik key is not defined

---

lib/classes/eik-config.js
test/classes/eik-config.test.js

Files with a leading `.` character were incorrectly being picked up as wrong. This PR passes the keys through the URL module to normalise pathnames.
```json
{
"files": {
"./": "etc"
}
}
```

fix: handle file keys starting with . correctly

---

.eslintignore
.gitignore
.prettierignore
package.json
tsconfig.json

This PR adds automated type definition building whenever a new version is published via a pre-publish hook. Type definitions are not committed to source control.

chore(build): add type definition file to published package

---

lib/classes/eik-config.js

Used madge to detect circular dependencies. `npx madge -c .`
```
✖ Found 2 circular dependencies!
1) lib/classes/eik-config.js > lib/helpers/index.js > lib/helpers/config-store.js
2) lib/classes/eik-config.js > lib/helpers/index.js > lib/helpers/get-defaults.js
```
This PR fixes them

fix: update require statements to avoid circular dependencies

---

package.json
packages/common-config-loader/package.json

Depending on files from `file:` breaks when the modules have been published.

Fix workspace deps

---

lib/helpers/config-store.js
lib/helpers/get-defaults.js
test/helpers/config-store.test.js

Makes it possible to pass an exact path to a config file (either package.json or eik.json) to the get-defaults method used in the cli commands. Non breaking backwards compatible change.
Part of the work needed to solve https://github.com/eik-lib/cli/issues/553

Add load exact method

---

eikjson.d.ts
lib/schemas/eikjson.schema.json
lib/schemas/validate.js

VS Code complained the schema couldn't be found.

fix: use the correct upstream schema link for ajv 

---

eikjson.d.ts
lib/helpers/type-slug.js
lib/helpers/type-title.js
lib/schemas/assert.js
lib/schemas/eikjson.schema.json
lib/validators/index.js
test/schemas/assert.test.js

Step 1 in adding a new namespace.
After this, step 2 is a minor update to @eik/core and step 3 is then adding routes to @eik/service. In that order due to:
```mermaid
graph TD;
eik/service-->eik/core;
eik/core-->eik/common;
```

feat: add support for Eik image type

---

.github/workflows/test.yml
lib/classes/eik-config.js
lib/classes/local-file-location.js
lib/classes/resolved-files.js
lib/helpers/path-slashes.js
lib/helpers/resolve-files.js
test/classes/eik-config/mappings.test.js
test/helpers/config-store.test.js
test/helpers/resolve-files.test.js

Windows paths threw a spanner in the works. This might not be the
optimal solution for outside modules, in which case I'm open to
changing the behavior to maintain win32 style paths on that OS.
The reasoning here is to keep in line with glob (which recommends
only using forward slashes in patterns) and the URLs which end up
on the Eik server (which, being HTTP URLs, use forward slash).
This should hopefully fix an issue Windows users have with the Eik
CLI not finding the files configured in eik.json

fix: keep internal consistency with glob and paths
